name: Release & Publish to NPM
on:
  push:
    branches:
      - production
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Initialize Git user
        run: git config --global user.email "EMAIL_HERE"
          git config --global user.name "Release Workflow"
      - name: Initialize the NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run Release
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: End message
        run: echo 'All done!'
